site_name: Documentation

theme:
  name: "material"

plugins:
  - mkdocstrings

nav:
  - Home: index.md
  - How-To Guides: how-to-guide.md
  - Reference: reference.md
  
docs_dir: assets/docs_md/

site_dir: docs/